
% connect to the database
load_db_params;
conn = database(datasource_name, user_name, password);

% if we are including degradation rate of change information (slope and
% intercept from 1D polyfit function)
if flight_num > lookback
    % these must match what is in the database (in order)
    degradation_tb_cols = {'flight_id', ...
                            'q_deg', ...
                            'q_var', ...
                            'q_slope', ...
                            'q_intercept', ...
                            'r_deg', ...
                            'r_var', ...
                            'r_slope', ...
                            'r_intercept', ...
                            'm_deg', ...
                            'm_var', ...
                            'm_slope', ...
                            'm_intercept', ...
                            'uav_id'};
    % these must match the variables in the workspace with a one-to-one 
    % relationship on the columns above
    degradation_tb = table(flight_id, ...
                           q_deg(flight_num), ...
                           q_std, ...
                           q_poly(1), ...
                           q_poly(2), ...
                           r_deg(flight_num), ...
                           r_std, ...
                           r_poly(1), ...
                           r_poly(2), ...
                           m_deg(flight_num), ...
                           m_std, ...
                           m_poly(1), ...
                           m_poly(2), ...
                           uav.id, ...
                           'VariableNames', degradation_tb_cols);

% if we are not including slope and intercept
else
    % then the colum list is this
    degradation_tb_cols = {'flight_id', ...
                           'q_deg', ...
                           'q_var', ...
                           'r_deg', ...
                           'r_var', ...
                           'm_deg', ...
                           'm_var', ...
                           'uav_id'};
                       
    % and these are the parameters
    degradation_tb = table(flight_id, ...
                           q_deg(flight_num), ...
                           q_std, ...
                           r_deg(flight_num), ...
                           r_std, ...
                           m_deg(flight_num), ...
                           m_std, ...
                           uav.id, ...
                           'VariableNames', degradation_tb_cols);
end

% write the data to the database
sqlwrite(conn, 'flight_degradation_tb', degradation_tb);
conn.commit();
conn.close();
clear('database_name', 'datasource_name', 'host_name', 'user_name', 'password');

