
% connect to the database
load_db_params;
conn = database(datasource_name, user_name, password);

% these must match the columns in the db, null data columns can be ommited
% from this list as needed
flight_summary_cols = {'stop_code', ...
                       'z_start', ...
                       'z_end', ...
                       'v_start', ...
                       'v_end', ...
                       'avg_pos_err', ...
                       'max_pos_err', ...
                       'std_pos_err', ...
                       'avg_ctrl_err', ...
                       'max_ctrl_err', ...
                       'std_ctrl_err', ...
                       'distance', ...
                       'flight_time', ...
                       'avg_current', ...
                       'amp_hours', ...
                       'dt_start', ...
                       'dt_stop', ...
                       'trajectory_id', ...
                       'uav_id', ...
                       'flight_num'};
               
% these must match the variables in the workspace
flight_summary_tb = table(stop_code, ...
                          z_end, ...
                          v_end, ...
                          avg_pos_err, ...
                          max_pos_err, ...
                          std_pos_err, ...
                          avg_ctrl_err, ...
                          max_ctrl_err, ...
                          std_ctrl_err, ...
                          distance, ...
                          flight_time, ...
                          avg_current, ...
                          amp_hours, ...
                          dt_start, ...
                          dt_stop, ...
                          trajectory.id, ...
                          uav.id, ...
                          flight_num, ...
                          'VariableNames', flight_summary_cols);

% write the data to the database
sqlwrite(conn, 'flight_summary_tb', flight_summary_tb);
conn.commit();
conn.close();
clear('database_name', 'datasource_name', 'host_name', 'user_name', 'password');