
conn = database(datasource_name, user_name, password);

stochastic_tb_cols = {'mission_idx', ...
                    'pos_err_mu', ...
                    'pos_err_std', ...
                    'pos_std_mu', ...
                    'pos_std_std', ...
                    'ctrl_err_mu', ...
                    'ctrl_err_std', ...
                    'ctrl_std_mu', ...
                    'ctrl_std_std', ...
                    'z_end_mu', ...
                    'z_end_std', ...
                    'v_end_mu', ...
                    'v_end_std', ...
                    'flight_time_mu', ...
                    'flight_time_std', ...
                    'stop_codes1', ...
                    'stop_codes2', ...
                    'stop_codes3', ...
                    'r_deg_mu', ...
                    'r_deg_std', ...
                    'q_deg_mu', ...
                    'q_deg_std', ...
                    'm_deg_mu', ...
                    'm_deg_std', ...
                    'r_poly_delta_mu', ...
                    'r_poly_delta_std', ...
                    'r_poly_bias_mu', ...
                    'r_poly_bias_std', ...
                    'q_poly_delta_mu', ...
                    'q_poly_delta_std', ...
                    'q_poly_bias_mu', ...
                    'q_poly_bias_std', ...
                    'm_poly_delta_mu', ...
                    'm_poly_delta_std', ...
                    'm_poly_bias_mu', ...
                    'm_poly_bias_std', ...
                    'mission_id_start', ...
                    'mission_id_stop'};
    

stochastic_tb = table(mission_idx, ...
                      avg_pos_err_dist(mission_idx, 1), ...
                      avg_pos_err_dist(mission_idx, 2), ...
                      std_pos_err_dist(mission_idx, 1), ...
                      std_pos_err_dist(mission_idx, 2), ...
                      avg_ctrl_err_dist(mission_idx, 1), ...
                      avg_ctrl_err_dist(mission_idx, 2), ...
                      std_ctrl_err_dist(mission_idx, 1), ...
                      std_ctrl_err_dist(mission_idx, 1), ...
                      z_ends_dist(mission_idx, 1), ...
                      z_ends_dist(mission_idx, 2), ...
                      v_ends_dist(mission_idx, 1), ...
                      v_ends_dist(mission_idx, 2), ...
                      flight_times_dist(mission_idx, 1), ...
                      flight_times_dist(mission_idx, 2), ...
                      stop_codes_dist(mission_idx, 1), ...
                      stop_codes_dist(mission_idx, 2), ...
                      stop_codes_dist(mission_idx, 3), ...
                      r_deg_dist(mission_idx, 1), ...
                      r_deg_dist(mission_idx, 2), ...
                      q_deg_dist(mission_idx, 1), ...
                      q_deg_dist(mission_idx, 2), ...
                      m_deg_dist(mission_idx, 1), ...
                      m_deg_dist(mission_idx, 2), ...                      
                      r_poly_dist(mission_idx, 1), ...
                      r_poly_dist(mission_idx, 2), ...
                      r_poly_dist(mission_idx, 3), ...
                      r_poly_dist(mission_idx, 4), ...
                      q_poly_dist(mission_idx, 1), ...
                      q_poly_dist(mission_idx, 2), ...
                      q_poly_dist(mission_idx, 3), ...
                      q_poly_dist(mission_idx, 4), ...
                      m_poly_dist(mission_idx, 1), ...
                      m_poly_dist(mission_idx, 2), ...
                      m_poly_dist(mission_idx, 3), ...
                      m_poly_dist(mission_idx, 4), ...
                      mission_id_start, ...
                      mission_id_stop, ...
                      'VariableNames', stochastic_tb_cols);

                
sqlwrite(conn, 'system_parameter_tb', stochastic_tb);
conn.commit();
conn.close();
