

twin_params_tb_cols = {'mission_id', ...
                       'trajectory_id', ...
                       'rul_hat', ...
                       'flight_time', ...
                       'distance', ...
                       'v_end', ...
                       'z_end', ...
                       'avg_err', ...
                       'q_deg', ...
                       'r_deg', ...
                       'm_deg', ...
                       'stop1', ...
                       'stop2', ...
                       'stop3', ...
                       'uav_id' };

twin_params_tb = table(mission_id, ...
                       trajectory.id, ...
                       rul_hat, ...
                       times(twin_ctr), ...
                       dist(twin_ctr), ...
                       vs(twin_ctr), ...
                       socs(twin_ctr), ...
                       errs(twin_ctr), ...
                       batterytwin.R0, ...
                       batterytwin.Q, ...
                       Motortwin2.Req, ...
                       int8(any(stop_code.Data(:,1))), ...
                       int8(any(stop_code.Data(:,2))), ...
                       int8(any(stop_code.Data(:,3))), ...
                       octomodel.id, ...
                       'VariableNames', twin_params_tb_cols);

sqlwrite(conn, 'twin_params_tb', twin_params_tb);
conn.commit();
clear('twin_params_tb', 'twin_params_tb_cols');